### ISSUE TITLE
Metronome

### ISSUE THREAD

**Issue by uiri** [uiri/trebletrouble#13]
The board should have a metronome mode.
Ideally, the beats per minute should be user-configurable.
- [x] Metronome works on dev machine
- [x] Metronome works on beagle bone
- [x] Zarro Boogs Found

**Comment by danrsles** [comment]
I can generate a string at a regular interval according to bpm, however when playing a .wav file consistantly it crashes after a few pulses

**Comment by uiri** [comment]
Blocked by #52

**Comment by uiri** [comment]
This is done 🎉
